function [] = myplot( X, Y, style ) 
%% function [] = myplot( X, Y, style ) 
%%
%% plot the requested (X,Y) pairs using the provided style
%%
%% style.base = '--r.'
%% style.MarkerSize = 1..
%% style.MarkerEdgeColor = 'k', 'b', ...
%% style.MarkerFaceColor = 'k', 'b', ...

plot( X,Y, style.base, ...
      'MarkerEdgeColor', style.MarkerEdgeColor, ...
      'MarkerFaceColor', style.MarkerFaceColor, ...
      'MarkerSize'     , style.MarkerSize );
