function [] = write_analytical_RME_QMMODEL(  )
% function [] = write_table_analytical_QMMODEL(  )
%
% write the verilog-A model for the RRAM resistive memory elements (RMEs)
% based on ./RME_QMMODEL_template.va . The model relies on the analytical QM conduction
% model equations implemented in ./verilog/analyticalModel.v
    
    baseFilename = 'RME_QMMODEL'; 
    writeVerilog( baseFilename );
    
    baseFilename = 'HOURGLASS';
    writeVerilog( baseFilename );
    
end

function writeVerilog( baseFilename )
    sourceFilename = [ baseFilename '.template.va' ];
        
    information = sprintf( '%s\n%s\n%s\n%s\n%s\n', ...
            '// ----------------------------------------------------------------------------------- ', ...
            '// File automatically generated by ./write_RME_QMModels/write_analytical_RME_QMMODEL.m ', ...                   
            [ '// File          : ' baseFilename   ], ...
            [ '// Creation date : ' datestr( now ) ], ...                           
            '// ----------------------------------------------------------------------------------- ' );
    commands.replace = {};
    commands.replace{end+1} = { '@@information' , information      };
    commands.replace{end+1} = { '@@modelName'   , baseFilename     };
    commands.replace{end+1} = { '@@tableFile'   , 'not applicable' };
    commands.replace{end+1} = { '@@ifTable'     , '// ' }; % comment out lines that start with @@ifTable
    commands.replace{end+1} = { '@@ifAnalytical', '   ' }; % do not comment out lines that start with @@ifAnalytical    
    
    [SUCCESS,MESSAGE,MESSAGEID] = mkdir( 'generated' );
    copyAndParseTemplate( sourceFilename, [ 'generated/' baseFilename '.va' ], commands );
end

   