function m2s = m2s_run(m2s,Rload1,Rload2,Rload3,Cload1,Cload2,Cload3,Rmemcell,Rmemhigh,Rmemlow,init_bl_1,init_bl_2,init_bl_3);function m2s_outstr = m2s_arg2str(m2s_instr);m2s_outstr = m2s_instr;for m2s_I=1:length(m2s_instr);if isnumeric(m2s_instr{m2s_I});if length(m2s_instr{m2s_I})>1m2s_outstr{m2s_I} = mat2str(m2s_instr{m2s_I},8);m2s_outstr{m2s_I} = m2s_outstr{m2s_I}(2:end-1);else;m2s_outstr{m2s_I} = num2str(m2s_instr{m2s_I},8);end;elseif islogical(m2s_instr{m2s_I});if length(m2s_instr{m2s_I})>1m2s_outstr{m2s_I} = mat2str(m2s_instr{m2s_I});m2s_outstr{m2s_I} = m2s_outstr{m2s_I}(2:end-1);else;m2s_outstr{m2s_I} = mat2str(m2s_instr{m2s_I});end;end;end;end;function m2s_outstr=m2s_cell2str(m2s_instr);m2s_outstr=cell2mat(cellfun(@(m2s_x) [m2s_x sprintf('\n')],m2s_instr,'UniformOutput',0));m2s_outstr=m2s_outstr(1:end-1);end;function varargout = m2s_emptyfn(varargin);throwAsCaller(MException('M2S:FnErr','function called before it has been initialized with $include, $insert or $import'));end;
m2s_file_memarray();
function m2s_file_memarray(); m2s.memarray.currentline = 0;function m2s_write(m2s_format,m2s_args);m2s_args=m2s_arg2str(m2s_args);if iscell(m2s_format);m2s_format=m2s_cell2str(m2s_format);end;m2s.memarray.currentline=m2s.memarray.currentline+1;m2s.memarray.outstr{m2s.memarray.currentline}=sprintf(m2s_format,m2s_args{:});end;
m2s_write('simulator lang=spectre',{});
m2s_write('',{});
m2s_write('subckt memarray ( bl_1 bl_2 sel1_1 sel1_2 sel1_3 sel2_1 sel2_2 sel2_3 wl_1 wl_2 wl_3 sl_1 sl_2 sl_3 vload_1 vload_2 vload_3 gnd vdd )',{});
m2s_write('',{});
m2s_write('// mem cell branch',{});
m2s_write('xsel1_1 node1_1 sel1_1 vload_1 vdd MOSP',{});
m2s_write('rload_1 (node1_1 bl_1) resistor r=%s',{Rload1});
m2s_write('',{});
m2s_write('rmemcell (bl_1 node2_1) resistor r=%s',{Rmemcell});
m2s_write('msl_1 node2_1 wl_1 sl_1 gnd MOSN',{});
m2s_write('',{});
m2s_write('cload_1 (bl_1 gnd) capacitor c=%s',{Cload1});
m2s_write('xsel2_1 bl_1 sel2_1 gnd gnd MOSN',{});
m2s_write('',{});
m2s_write('// high ref cell branch',{});
m2s_write('xsel1_2 node1_2 sel1_2 vload_2 vdd MOSP',{});
m2s_write('rload_2 (node1_2 bl_2) resistor r=%s',{Rload2});
m2s_write('',{});
m2s_write('rmemhigh (bl_2 node2_2) resistor r=%s',{Rmemhigh});
m2s_write('xsl_2 node2_2 wl_2 sl_2 gnd MOSN',{});
m2s_write('',{});
m2s_write('cload_2 (bl_2 gnd) capacitor c=%s',{Cload2});
m2s_write('xsel2_2 bl_2 sel2_2 gnd gnd MOSN',{});
m2s_write('',{});
m2s_write('// low ref cell branch',{});
m2s_write('xsel1_3 node1_3 sel1_3 vload_3 vdd MOSP',{});
m2s_write('rload_3 (node1_3 bl_3) resistor r=%s',{Rload3});
m2s_write('',{});
m2s_write('rmemlow (bl_3 node2_3) resistor r=%s',{Rmemlow});
m2s_write('msl_3 node2_3 wl_3 sl_3 gnd MOSN',{});
m2s_write('',{});
m2s_write('cload_3 (bl_3 gnd) capacitor c=%s',{Cload3});
m2s_write('xsel2_3 bl_3 sel2_3 gnd gnd MOSN',{});
m2s_write('',{});
m2s_write('aliasbl ( bl_2 bl_3 ) vsource type=dc dc=0',{});
m2s_write('',{});
m2s_write('ic bl_1=%s',{init_bl_1});
m2s_write('ic bl_2=%s',{init_bl_2});
m2s_write('ic bl_3=%s',{init_bl_3});
m2s_write('',{});
m2s_write('',{});
m2s_write('ends memarray',{});
end
end